<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        DB::table('products')->insert([
            [
                'name' => 'Шоколадний торт Premium',
                'description' => 'Ніжний шоколадний бісквіт з кремом на бельгійському шоколаді.',
                'price' => 890.00,
                'weight' => 1.20,
                'height' => 12,
                'category_id' => 1,
                'image_path' => 'products/choco-premium.jpg',
                'stock' => 12,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Медовик Класичний',
                'description' => 'Домашній медовик з вершковим кремом.',
                'price' => 620.00,
                'weight' => 1.00,
                'height' => 10,
                'category_id' => 1,
                'image_path' => 'products/medovyk.jpg',
                'stock' => 8,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Чізкейк Нью-Йорк',
                'description' => 'Класичний сирний чізкейк з ваніллю.',
                'price' => 740.00,
                'weight' => 0.95,
                'height' => 8,
                'category_id' => 1,
                'image_path' => 'products/cheesecake.jpg',
                'stock' => 10,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Капкейк Ванільний',
                'description' => 'Повітряний капкейк з крем-чізом.',
                'price' => 85.00,
                'weight' => 0.12,
                'height' => 7,
                'category_id' => 2,
                'image_path' => 'products/cupcake-vanilla.jpg',
                'stock' => 35,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Капкейк Шоколадний',
                'description' => 'Шоколадний капкейк з карамельною начинкою.',
                'price' => 95.00,
                'weight' => 0.13,
                'height' => 7,
                'category_id' => 2,
                'image_path' => 'products/cupcake-choco.jpg',
                'stock' => 28,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Макарон Фісташка',
                'description' => 'Французький десерт з фісташковим ганашем.',
                'price' => 55.00,
                'weight' => 0.03,
                'height' => 4,
                'category_id' => 3,
                'image_path' => 'products/macaroon-pistachio.jpg',
                'stock' => 50,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Макарон Малина',
                'description' => 'Макарон з малиновою начинкою.',
                'price' => 55.00,
                'weight' => 0.03,
                'height' => 4,
                'category_id' => 3,
                'image_path' => 'products/macaroon-raspberry.jpg',
                'stock' => 46,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Еклер Кавовий',
                'description' => 'Заварне тісто з ніжним кавовим кремом.',
                'price' => 78.00,
                'weight' => 0.11,
                'height' => 5,
                'category_id' => 4,
                'image_path' => 'products/eclair-coffee.jpg',
                'stock' => 24,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Еклер Ванільний',
                'description' => 'Класичний еклер з ванільним кремом.',
                'price' => 75.00,
                'weight' => 0.11,
                'height' => 5,
                'category_id' => 4,
                'image_path' => 'products/eclair-vanilla.jpg',
                'stock' => 20,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Брауні Горіховий',
                'description' => 'Насичений шоколадний брауні з волоським горіхом.',
                'price' => 120.00,
                'weight' => 0.18,
                'height' => 4,
                'category_id' => 5,
                'image_path' => 'products/brownie-nuts.jpg',
                'stock' => 18,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Печиво Імбирне',
                'description' => 'Ароматне печиво з імбиром та корицею.',
                'price' => 140.00,
                'weight' => 0.25,
                'height' => 3,
                'category_id' => 6,
                'image_path' => 'products/ginger-cookie.jpg',
                'stock' => 40,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Печиво Шоколадне',
                'description' => 'Хрустке печиво з шматочками шоколаду.',
                'price' => 135.00,
                'weight' => 0.25,
                'height' => 3,
                'category_id' => 6,
                'image_path' => 'products/choco-cookie.jpg',
                'stock' => 37,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Тарт Лимонний',
                'description' => 'Пісочна основа та лимонний курд.',
                'price' => 310.00,
                'weight' => 0.42,
                'height' => 5,
                'category_id' => 7,
                'image_path' => 'products/lemon-tart.jpg',
                'stock' => 9,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Тарт Ягідний',
                'description' => 'Сезонні ягоди та заварний крем.',
                'price' => 340.00,
                'weight' => 0.45,
                'height' => 5,
                'category_id' => 7,
                'image_path' => 'products/berry-tart.jpg',
                'stock' => 7,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Тірамісу Класичний',
                'description' => 'Італійський десерт з маскарпоне та кавою.',
                'price' => 390.00,
                'weight' => 0.55,
                'height' => 6,
                'category_id' => 8,
                'image_path' => 'products/tiramisu.jpg',
                'stock' => 11,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
